### ISSUE TITLE
Incorrect destination port setting in example task.json

### ISSUE THREAD

**Issue by JohanDehn** [br-automation-com/vscode-brautomationtools#39]
Incorrect port setting in example task.json file in the extension details. 

"destinationPort": 11160, 

should  be

  "destinationPort": 11169,

`
 {
            "label": "BrAsTransfer: ArSim with default install settings",
            "type": "BrAsTransfer",
            "pviConnectionSettings": {
                "deviceInterface": "tcpip",
                "sourceNode": 42,
                "destinationAddress": "127.0.0.1",
                "destinationPort": 11160,
                "communicationTimeout": 1000,
                "connectionEstablishedTimeout": 60
            },
`

**Comment by Radeonmann** [comment]
Hi Johan

This PVI configuration template is the one for the ArSim connection. If I'm not mistaken, the default ANSL port in ArSim is 11160 and the default port for real PLCs is 11169.

Just to be sure I will check it again and close it / fix it depending on the result.

**Comment by JohanDehn** [comment]
Yes your absolutely right, and I am wrong, were running in simulation of a real PLC. 
I have checked verified that the ARSIM port is 11160. Close the case

**Comment by Radeonmann** [comment]
I reopened the issue. because it seems the port 11160 in the ArSim is only used for INA.

The template which is generated from the extension does not work.

The extension uses the `/PT=<port>` parameter for the port in the connection settings.
Automation Studio uses `/REPO=11160 ... /PT=11169` for the connection settings with a default ArSim configuration.

![image](https://user-images.githubusercontent.com/13839232/225904810-4fc8738e-4c75-4c91-9a2b-a75f552cc261.png)

According to the AS help `/REPO` only exist for backwards compatibility with INA connections, and if both `/PT=<port>` and `/REPO=<port>` are set, `/PT` will win.
![image](https://user-images.githubusercontent.com/13839232/225905436-45002bf1-d1f5-4211-a33b-1e40fdddbba9.png)

Therefore Automation Studio also uses port 11169 for ANSL in ArSim and the template in the extension needs to be adjusted.

**Comment by Radeonmann** [comment]
Fixed, will be in next release
